language: python

jobs:
  include:
    - name: "Python 3.6 on default Linux (Xenial): pip installation with user package"
      os: linux
      dist: xenial
      language: python
      python: "3.6"           # this works for Linux but is ignored on macOS or Windows
      env:
        - INSTALL='pip' ENV='default'
    - name: "Python 3.6 on default Linux (Xenial): pip installation with additional tests package"
        os: linux
        dist: xenial
        language: python
        python: "3.6"           # this works for Linux but is ignored on macOS or Windows
        env:
          - INSTALL='pip' ENV='tests'
    - name: "Python 3.6 on default Linux (Xenial): pip installation with additionnal gdist package"
        os: linux
        dist: xenial
        language: python
        python: "3.6"           # this works for Linux but is ignored on macOS or Windows
        env:
          - INSTALL='pip' ENV='gdist'
    - name: "Python 3.6 on default Linux (Xenial): complete pip installation"
        os: linux
        dist: xenial
        language: python
        python: "3.6"           # this works for Linux but is ignored on macOS or Windows
        env:
          - INSTALL='pip' ENV='full'

    - name: "Python 3.6 on default macOSX (10.13)"
      os: osx
      osx_image: xcode9.4
      language: shell         # small hack as python is not fully supported under macOS
      env:
        - TRAVIS_PYTHON_VERSION="3.6" INSTALL='pip' ENV='default'
    - name: "Python 3.6 on default macOSX (10.13)"
        os: osx
        osx_image: xcode9.4
        language: shell         # small hack as python is not fully supported under macOS
        env:
          - TRAVIS_PYTHON_VERSION="3.6" INSTALL='pip' ENV='tests'
    - name: "Python 3.6 on default macOSX (10.13)"
        os: osx
        osx_image: xcode9.4
        language: shell         # small hack as python is not fully supported under macOS
        env:
          - TRAVIS_PYTHON_VERSION="3.6" INSTALL='pip' ENV='gdist'
    - name: "Python 3.6 on default macOSX (10.13)"
        os: osx
        osx_image: xcode9.4
        language: shell         # small hack as python is not fully supported under macOS
        env:
          - TRAVIS_PYTHON_VERSION="3.6"
    - name: "Python 3.6 on default macOSX (10.13)"
        os: osx
        osx_image: xcode9.4
        language: shell         # small hack as python is not fully supported under macOS
        env:
          - TRAVIS_PYTHON_VERSION="3.6" INSTALL='pip' ENV='full'




# not needed step, save time
before_install: skip
# command to install dependencies
install:  source continuous_integration/install.sh

# command to run tests
script: source continuous_integration/tests.sh

after_success:
  - coveralls || true

# automatically upload package on Pypi if tagged as a release
deploy:
  provider: pypi
  username: "__token__"
  password: "Your PyPI API token, including the pypi- prefix"  # to be changed
  skip_existing: true  # to avoid error when multiple builds
  distributions: "sdist bdist_wheel"
  on:
    tags: true  # deploy package only on set tags
