distrib:  xenial
language: python
python:
  - "3.6"

  
# command to install dependencies
install:  source continous_integration/install.sh

# command to run tests
script:
  # style check
  - flake8 slam/
  - flake8 examples/
  - flake8 tests/
  - autopep8 --recursive --aggressive --diff --exit-code slam/
  - autopep8 --recursive --aggressive --diff --exit-code examples/
  - autopep8 --recursive --aggressive --diff --exit-code tests/
  #- pytest
  - pytest -W default --cov=slam/

  # make sure examples still work
  #- cd examples
  #- for f in *py*; do python "$f"; done
  #- cd ..

after_success:
  - coveralls || true
