
jobs:
  include:
    - name: "Python 3.6 on default Linux (Xenial)"
      os: linux
      dist: xenial
      language: python
      python: "3.6"           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.6 on default macOSX (10.13)"
      os: osx
      osx_image: xcode9.4
      language: shell
      python: "3.6"



before_install: skip
# command to install dependencies
install:  source continuous_integration/install.sh

# command to run tests
script: source continuous_integration/tests.sh

after_success:
  - coveralls || true
