os:
  - linux
  - osx
dist: xenial
language: python
python:
  - "3.6"

# command to install dependencies
install:  source continuous_integration/install.sh

# command to run tests
script: source continuous_integration/tests.sh

after_success:
  - coveralls || true
